apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: todos.honk.ci
spec:
  group: honk.ci
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                hint:
                  type: string
                todo:
                  type: string
              required:
              - todo
      additionalPrinterColumns:
      - name: Todo
        type: string
        description: "An important task"
        jsonPath: ".spec.todo"
  scope: Cluster
  names:
    plural: todos
    singular: todo
    kind: Todo
    shortNames:
    - td
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: todo-view-crd
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups: ["honk.ci"]
  resources: ["todos"]
  verbs: ["get", "list", "watch"]
---
# Allow EVERYONE to view todo items
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: authenticated-view-todo-crd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: todo-view-crd
subjects:
- kind: Group
  name: system:authenticated
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: authenticated-view-cluster-crds
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
---
# Allow EVERYONE to view cluster level CRDs so that they may find todos
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: authenticated-view-cluster-crd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: authenticated-view-cluster-crds
subjects:
- kind: Group
  name: system:authenticated