apiVersion: v1
kind: ServiceAccount
metadata:
  name: groundskeeper
  namespace: garden
  labels:
    rake: 'true'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: groundskeeper
  namespace: garden
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: groundskeeper
  namespace: garden
---
# groundskeeper has access to spin things up in the pub
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: groundskeeper
  namespace: pub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: groundskeeper
  namespace: garden
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: groundskeeper
  namespace: garden
  labels:
    rake: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      rake: 'true'
  template:
    metadata:
      labels:
        rake: 'true'
    spec:
      serviceAccountName: groundskeeper
      containers:
      - name: groundskeeper
        image: nginx:stable-alpine
        resources:
          limits:
            memory: 10Mi
            cpu: 100m
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: rake
      volumes:
      - name: rake
        configMap:
          name: rake
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rake
  namespace: garden
data:
  index.html: "<html>\n<head>\n\t<meta charset=\"UTF-8\">\n</head>\n<body>\n<pre>\n\n
    \ ▒▒██\n░░▒▒▒▒▓▓\n  ▓▓▒▒▒▒▓▓\n    ▓▓▓▓▒▒▒▒\n      ▒▒▓▓▒▒██\n        ▒▒▓▓▒▒▓▓\n
    \         ▒▒▒▒▒▒▓▓\n            ▓▓▒▒▒▒▒▒\n              ▓▓▒▒▒▒\n                ▓▓▒▒▓▓\n
    \               ░░▓▓▒▒▓▓\n                  ▒▒▒▒▒▒▒▒\n                    ▓▓▒▒▒▒▒▒\n
    \                     ██▒▒▒▒▒▒\n                        ▓▓▒▒▒▒░░\n                          ▓▓▒▒▒▒░░\n
    \                           ▓▓▒▒▒▒░░\n                            ░░▓▓▒▒▒▒\n                              ░░▓▓▒▒██\n
    \                               ▒▒▒▒▒▒▒▒\n                                  ▓▓▒▒▒▒░░\n
    \                                   ▓▓▒▒▒▒▒▒\n                                      ▓▓▒▒▒▒▒▒\n
    \                                     ░░▓▓▒▒▒▒\n                                        ░░▓▓▒▒▒▒\n
    \                                           ██▒▒▒▒░░\n                                              ▓▓▒▒▒▒░░\n
    \                                               ▓▓▒▒▒▒\n                                                ░░▒▒▒▒▓▓\n
    \                                                 ▒▒▒▒▒▒░░\n                                                    ▓▓▒▒▒▒░░\n
    \                                                     ██▒▒▒▒\n                                                        ▓▓▒▒██\n
    \                                                         ▓▓▒▒░░\n                                                            ▒▒▒▒▒▒\n
    \                                                           ░░▒▒▒▒▒▒\n                                                              ▒▒▒▒▒▒██\n
    \                                                               ▒▒▒▒▒▒▓▓\n                                                                  ▒▒▒▒▒▒▒▒\n
    \                                                                   ▒▒▒▒▒▒░░\n
    \                                                                     ▓▓▒▒▒▒\n
    \                                                                       ▒▒▒▒▒▒\n
    \                                                                         ▓▓▒▒▓▓\n
    \                                                                         ░░▒▒▒▒▓▓\n
    \                                                                           ░░▒▒▒▒▒▒\n
    \                                                                             ▓▓▒▒▒▒▒▒\n
    \                                                                               ▓▓▒▒▒▒░░\n
    \                                                                                 ██▒▒▒▒░░\n
    \                                                                                   ▓▓▒▒▒▒░░\n
    \                                                                                     ▓▓▓▓▓▓\n
    \                                                                                       ▓▓▓▓██\n
    \                                                                                       ░░▒▒▓▓▒▒\n
    \                                                                                         ░░▒▒▓▓░░\n
    \                                                                                           ▒▒▒▒▓▓░░\n
    \                                                                                             ▒▒▓▓▓▓▓▓░░\n
    \                                                                                               ▓▓▓▓▓▓▓▓▓▓▓▓░░\n
    \                                                                                                 ▒▒▓▓▓▓▓▓▓▓▒▒▓▓▒▒░░\n
    \                                                                                                 ▓▓▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▓▓██\n
    \                                                                                                 ▒▒▒▒▒▒▓▓▓▓▓▓▓▓▒▒▒▒▓▓▓▓░░▒▒▒▒▓▓▓▓\n
    \                                                                                                 ░░▒▒▒▒▒▒██▓▓▓▓▓▓░░▓▓▓▓▒▒▓▓░░
    \ ░░▓▓▓▓\n                                                                                                    ▓▓▓▓▓▓▓▓▓▓▓▓▒▒██▓▓▒▒▒▒
    \ ░░▓▓▒▒    ▓▓\n                                                                                                    ▒▒▓▓▓▓▓▓▒▒▒▒▓▓▓▓▒▒▒▒
    \ ▒▒▓▓░░  ▒▒▒▒  ▓▓\n                                                                                                      ▒▒▒▒▒▒▒▒▓▓▒▒▓▓▓▓
    \ ▓▓░░  ▒▒▓▓░░░░▓▓\n                                                                                                      ▓▓▓▓▓▓▒▒▒▒▓▓▓▓░░▒▒░░░░▓▓
    \   ▓▓▒▒  ▓▓\n                                                                                                      ▒▒▒▒░░▓▓▓▓▒▒░░▒▒
    \ ▓▓▒▒  ▓▓░░  ▒▒▓▓\n                                                                                                      ░░▓▓▒▒▓▓░░░░▓▓
    \ ▓▓  ▒▒▓▓  ░░▒▒  ░░░░\n                                                                                                      ▒▒▒▒▓▓
    \ ▒▒▒▒  ▓▓  ▓▓  ░░▓▓  ░░▓▓\n                                                                                                        ▓▓░░
    \ ▒▒░░▒▒░░▓▓  ▓▓  ░░▓▓  ░░\n                                                                                                        ▒▒░░▓▓
    \ ░░▓▓  ░░▒▒  ▓▓  ░░▓▓\n                                                                                                          ▒▒▓▓
    \ ▓▓  ▓▓  ▒▒░░░░▓▓\n                                                                                                          ▓▓░░▒▒░░▒▒░░▓▓
    \ ▓▓░░░░░░\n                                                                                                          ▒▒
    \ ▓▓  ▓▓  ▓▓▒▒  ▓▓\n                                                                                                          ░░▒▒░░
    \   ▓▓  ▓▓░░\n                                                                                                            ▓▓
    \ ▓▓  ▒▒▒▒\n                                                                                                            ░░▒▒▒▒▒▒\n\n</pre>\n</body>\n</html>\n"
