apiVersion: v1
kind: ServiceAccount
metadata:
  name: old-man
  namespace: pub
  labels:
    dartboard: 'true'
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: old-man
  namespace: pub
  labels:
    dartboard: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      dartboard: 'true'
  template:
    metadata:
      labels:
        dartboard: 'true'
    spec:
      serviceAccountName: old-man
      containers:
      - name: old-man
        image: nginx:stable-alpine
        resources:
          limits:
            memory: 10Mi
            cpu: 100m
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: dartboard
      volumes:
      - name: dartboard
        configMap:
          name: dartboard
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dartboard
  namespace: pub
data:
  index.html: |2
    <html>
    <head>
    <meta charset="UTF-8">
    </head>
    <body>
    <pre>
        ,-'"""`-,    ,-----.
      ,' \ _|_ / `.  | 501 |
     /`.,'\ | /`.,'\ `-----'  |
    (  /`. \|/ ,'\  )      |  H
    |--|--;=@=:--|--|   |  H  U
    (  \,' /|\ `./  )   H  U  |
     \,'`./ | \,'`./    U  | (|)
      `. / """ \ ,'     | (|)
        '-._|_,-`      (|)
    </pre>
    </body>
    </html>
