---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: woman
  namespace: pub
  labels:
    flower: 'true'
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: woman
  namespace: pub
  labels:
    flower: 'true'
spec:
  replicas: 2
  selector:
    matchLabels:
      flower: 'true'
  serviceName: table
  template:
    metadata:
      labels:
        flower: 'true'
    spec:
      serviceAccountName: woman
      containers:
      - name: nginx
        image: nginx:stable-alpine
        resources:
          limits:
            memory: 10Mi
            cpu: 100m
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: flower
      volumes:
      - name: flower
        configMap:
          name: flower
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flower
  namespace: pub
data:
  index.html: |2
    <html>
    <head>
    <meta charset="UTF-8">
    </head>
    <body>
    <pre>
            .-~~-.--.
           :         )
     .~ ~ -.\       /.- ~~ .
     >       `.   .'       <
    (         .- -.         )
     `- -.-~  `- -'  ~-.- -'
       (        :        )           _ _ .-:
        ~--.    :    .--~        .-~  .-~  }
            ~-.-^-.-~ \_      .~  .-~   .~
                     \ \'     \ '_ _ -~
                      `.`.    //
             . - ~ ~-.__`.`-.//
         .-~   . - ~  }~ ~ ~-.~-.
       .' .-~      .-~       :/~-.~-./:
      /_~_ _ . - ~                 ~-.~-._
                                       ~-.<
    </pre>
    </body>
    </html>
