apiVersion: v1
kind: Service
metadata:
  name: bell
  namespace: home
spec:
  selector:
    beautiful: 'true'
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: bell
  namespace: model-village
  labels:
    location: tower
data:
  bell.yaml: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: bell
      namespace: home
      annotations:
        description: "A beautiful golden bell."
      labels:
        beautiful: 'true'
    spec:
      containers:
      - name: bell
        image: mrbobbytables/bell:latest
        ports:
        - containerPort: 80